# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuildingMapProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FloorProto_pb2
import CoordinatesProto_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BuildingMapProto.proto',
  package='com.navatar.protobufs',
  serialized_pb=_b('\n\x16\x42uildingMapProto.proto\x12\x15\x63om.navatar.protobufs\x1a\x10\x46loorProto.proto\x1a\x16\x43oordinatesProto.proto\"\xc1\x01\n\x0b\x42uildingMap\x12:\n\x0eminCoordinates\x18\x01 \x01(\x0b\x32\".com.navatar.protobufs.Coordinates\x12:\n\x0emaxCoordinates\x18\x02 \x01(\x0b\x32\".com.navatar.protobufs.Coordinates\x12\x0c\n\x04name\x18\x03 \x01(\t\x12,\n\x06\x66loors\x18\x04 \x03(\x0b\x32\x1c.com.navatar.protobufs.Floor')
  ,
  dependencies=[FloorProto_pb2.DESCRIPTOR,CoordinatesProto_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BUILDINGMAP = _descriptor.Descriptor(
  name='BuildingMap',
  full_name='com.navatar.protobufs.BuildingMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minCoordinates', full_name='com.navatar.protobufs.BuildingMap.minCoordinates', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxCoordinates', full_name='com.navatar.protobufs.BuildingMap.maxCoordinates', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.navatar.protobufs.BuildingMap.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floors', full_name='com.navatar.protobufs.BuildingMap.floors', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=285,
)

_BUILDINGMAP.fields_by_name['minCoordinates'].message_type = CoordinatesProto_pb2._COORDINATES
_BUILDINGMAP.fields_by_name['maxCoordinates'].message_type = CoordinatesProto_pb2._COORDINATES
_BUILDINGMAP.fields_by_name['floors'].message_type = FloorProto_pb2._FLOOR
DESCRIPTOR.message_types_by_name['BuildingMap'] = _BUILDINGMAP

BuildingMap = _reflection.GeneratedProtocolMessageType('BuildingMap', (_message.Message,), dict(
  DESCRIPTOR = _BUILDINGMAP,
  __module__ = 'BuildingMapProto_pb2'
  # @@protoc_insertion_point(class_scope:com.navatar.protobufs.BuildingMap)
  ))
_sym_db.RegisterMessage(BuildingMap)


# @@protoc_insertion_point(module_scope)
