# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoordinatesProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CoordinatesProto.proto',
  package='com.navatar.protobufs',
  serialized_pb=_b('\n\x16\x43oordinatesProto.proto\x12\x15\x63om.navatar.protobufs\"#\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='com.navatar.protobufs.Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='com.navatar.protobufs.Coordinates.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='com.navatar.protobufs.Coordinates.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATES,
  __module__ = 'CoordinatesProto_pb2'
  # @@protoc_insertion_point(class_scope:com.navatar.protobufs.Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)


# @@protoc_insertion_point(module_scope)
