# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FloorProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LandmarkProto_pb2
import NavigableSpaceProto_pb2
import MinimapProto_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FloorProto.proto',
  package='com.navatar.protobufs',
  serialized_pb=_b('\n\x10\x46loorProto.proto\x12\x15\x63om.navatar.protobufs\x1a\x13LandmarkProto.proto\x1a\x19NavigableSpaceProto.proto\x1a\x12MinimapProto.proto\"\xbc\x01\n\x05\x46loor\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x32\n\tlandmarks\x18\x02 \x03(\x0b\x32\x1f.com.navatar.protobufs.Landmark\x12>\n\x0fnavigableSpaces\x18\x03 \x03(\x0b\x32%.com.navatar.protobufs.NavigableSpace\x12/\n\x07minimap\x18\x04 \x01(\x0b\x32\x1e.com.navatar.protobufs.Minimap')
  ,
  dependencies=[LandmarkProto_pb2.DESCRIPTOR,NavigableSpaceProto_pb2.DESCRIPTOR,MinimapProto_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLOOR = _descriptor.Descriptor(
  name='Floor',
  full_name='com.navatar.protobufs.Floor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='com.navatar.protobufs.Floor.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='com.navatar.protobufs.Floor.landmarks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='navigableSpaces', full_name='com.navatar.protobufs.Floor.navigableSpaces', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimap', full_name='com.navatar.protobufs.Floor.minimap', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=300,
)

_FLOOR.fields_by_name['landmarks'].message_type = LandmarkProto_pb2._LANDMARK
_FLOOR.fields_by_name['navigableSpaces'].message_type = NavigableSpaceProto_pb2._NAVIGABLESPACE
_FLOOR.fields_by_name['minimap'].message_type = MinimapProto_pb2._MINIMAP
DESCRIPTOR.message_types_by_name['Floor'] = _FLOOR

Floor = _reflection.GeneratedProtocolMessageType('Floor', (_message.Message,), dict(
  DESCRIPTOR = _FLOOR,
  __module__ = 'FloorProto_pb2'
  # @@protoc_insertion_point(class_scope:com.navatar.protobufs.Floor)
  ))
_sym_db.RegisterMessage(Floor)


# @@protoc_insertion_point(module_scope)
