# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LandmarkProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CoordinatesProto_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LandmarkProto.proto',
  package='com.navatar.protobufs',
  serialized_pb=_b('\n\x13LandmarkProto.proto\x12\x15\x63om.navatar.protobufs\x1a\x16\x43oordinatesProto.proto\"\x8f\x02\n\x08Landmark\x12\x34\n\x08location\x18\x01 \x01(\x0b\x32\".com.navatar.protobufs.Coordinates\x12\x0c\n\x04name\x18\x02 \x01(\t\x12:\n\x04type\x18\x03 \x01(\x0e\x32,.com.navatar.protobufs.Landmark.LandmarkType\x12\x35\n\tparticles\x18\x04 \x03(\x0b\x32\".com.navatar.protobufs.Coordinates\"L\n\x0cLandmarkType\x12\x08\n\x04\x44OOR\x10\x01\x12\x18\n\x14HALLWAY_INTERSECTION\x10\x02\x12\n\n\x06STAIRS\x10\x03\x12\x0c\n\x08\x45LEVATOR\x10\x04')
  ,
  dependencies=[CoordinatesProto_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LANDMARK_LANDMARKTYPE = _descriptor.EnumDescriptor(
  name='LandmarkType',
  full_name='com.navatar.protobufs.Landmark.LandmarkType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOOR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HALLWAY_INTERSECTION', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAIRS', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ELEVATOR', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=266,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_LANDMARK_LANDMARKTYPE)


_LANDMARK = _descriptor.Descriptor(
  name='Landmark',
  full_name='com.navatar.protobufs.Landmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='com.navatar.protobufs.Landmark.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.navatar.protobufs.Landmark.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.navatar.protobufs.Landmark.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='particles', full_name='com.navatar.protobufs.Landmark.particles', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LANDMARK_LANDMARKTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=342,
)

_LANDMARK.fields_by_name['location'].message_type = CoordinatesProto_pb2._COORDINATES
_LANDMARK.fields_by_name['type'].enum_type = _LANDMARK_LANDMARKTYPE
_LANDMARK.fields_by_name['particles'].message_type = CoordinatesProto_pb2._COORDINATES
_LANDMARK_LANDMARKTYPE.containing_type = _LANDMARK
DESCRIPTOR.message_types_by_name['Landmark'] = _LANDMARK

Landmark = _reflection.GeneratedProtocolMessageType('Landmark', (_message.Message,), dict(
  DESCRIPTOR = _LANDMARK,
  __module__ = 'LandmarkProto_pb2'
  # @@protoc_insertion_point(class_scope:com.navatar.protobufs.Landmark)
  ))
_sym_db.RegisterMessage(Landmark)


# @@protoc_insertion_point(module_scope)
