# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MinimapProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CoordinatesProto_pb2
import LandmarkProto_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MinimapProto.proto',
  package='com.navatar.protobufs',
  serialized_pb=_b('\n\x12MinimapProto.proto\x12\x15\x63om.navatar.protobufs\x1a\x16\x43oordinatesProto.proto\x1a\x13LandmarkProto.proto\"\xe2\x01\n\x07Minimap\x12\x10\n\x08sideSize\x18\x01 \x01(\x01\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x03 \x01(\x05\x12:\n\x0eminCoordinates\x18\x04 \x01(\x0b\x32\".com.navatar.protobufs.Coordinates\x12\x32\n\x05tiles\x18\x05 \x03(\x0b\x32#.com.navatar.protobufs.Minimap.Tile\x1a\x36\n\x04Tile\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\x05\x12\x11\n\tlandmarks\x18\x03 \x03(\x05')
  ,
  dependencies=[CoordinatesProto_pb2.DESCRIPTOR,LandmarkProto_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MINIMAP_TILE = _descriptor.Descriptor(
  name='Tile',
  full_name='com.navatar.protobufs.Minimap.Tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='com.navatar.protobufs.Minimap.Tile.row', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column', full_name='com.navatar.protobufs.Minimap.Tile.column', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='com.navatar.protobufs.Minimap.Tile.landmarks', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=317,
)

_MINIMAP = _descriptor.Descriptor(
  name='Minimap',
  full_name='com.navatar.protobufs.Minimap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sideSize', full_name='com.navatar.protobufs.Minimap.sideSize', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='com.navatar.protobufs.Minimap.rows', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columns', full_name='com.navatar.protobufs.Minimap.columns', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minCoordinates', full_name='com.navatar.protobufs.Minimap.minCoordinates', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='com.navatar.protobufs.Minimap.tiles', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MINIMAP_TILE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=317,
)

_MINIMAP_TILE.containing_type = _MINIMAP
_MINIMAP.fields_by_name['minCoordinates'].message_type = CoordinatesProto_pb2._COORDINATES
_MINIMAP.fields_by_name['tiles'].message_type = _MINIMAP_TILE
DESCRIPTOR.message_types_by_name['Minimap'] = _MINIMAP

Minimap = _reflection.GeneratedProtocolMessageType('Minimap', (_message.Message,), dict(

  Tile = _reflection.GeneratedProtocolMessageType('Tile', (_message.Message,), dict(
    DESCRIPTOR = _MINIMAP_TILE,
    __module__ = 'MinimapProto_pb2'
    # @@protoc_insertion_point(class_scope:com.navatar.protobufs.Minimap.Tile)
    ))
  ,
  DESCRIPTOR = _MINIMAP,
  __module__ = 'MinimapProto_pb2'
  # @@protoc_insertion_point(class_scope:com.navatar.protobufs.Minimap)
  ))
_sym_db.RegisterMessage(Minimap)
_sym_db.RegisterMessage(Minimap.Tile)


# @@protoc_insertion_point(module_scope)
