# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NavigableSpaceProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CoordinatesProto_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NavigableSpaceProto.proto',
  package='com.navatar.protobufs',
  serialized_pb=_b('\n\x19NavigableSpaceProto.proto\x12\x15\x63om.navatar.protobufs\x1a\x16\x43oordinatesProto.proto\"w\n\x0eNavigableSpace\x12\x39\n\routerBoundary\x18\x01 \x03(\x0b\x32\".com.navatar.protobufs.Coordinates\x12*\n\x05rings\x18\x02 \x03(\x0b\x32\x1b.com.navatar.protobufs.Ring\";\n\x04Ring\x12\x33\n\x07polygon\x18\x01 \x03(\x0b\x32\".com.navatar.protobufs.Coordinates')
  ,
  dependencies=[CoordinatesProto_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NAVIGABLESPACE = _descriptor.Descriptor(
  name='NavigableSpace',
  full_name='com.navatar.protobufs.NavigableSpace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outerBoundary', full_name='com.navatar.protobufs.NavigableSpace.outerBoundary', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rings', full_name='com.navatar.protobufs.NavigableSpace.rings', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=195,
)


_RING = _descriptor.Descriptor(
  name='Ring',
  full_name='com.navatar.protobufs.Ring',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='polygon', full_name='com.navatar.protobufs.Ring.polygon', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=256,
)

_NAVIGABLESPACE.fields_by_name['outerBoundary'].message_type = CoordinatesProto_pb2._COORDINATES
_NAVIGABLESPACE.fields_by_name['rings'].message_type = _RING
_RING.fields_by_name['polygon'].message_type = CoordinatesProto_pb2._COORDINATES
DESCRIPTOR.message_types_by_name['NavigableSpace'] = _NAVIGABLESPACE
DESCRIPTOR.message_types_by_name['Ring'] = _RING

NavigableSpace = _reflection.GeneratedProtocolMessageType('NavigableSpace', (_message.Message,), dict(
  DESCRIPTOR = _NAVIGABLESPACE,
  __module__ = 'NavigableSpaceProto_pb2'
  # @@protoc_insertion_point(class_scope:com.navatar.protobufs.NavigableSpace)
  ))
_sym_db.RegisterMessage(NavigableSpace)

Ring = _reflection.GeneratedProtocolMessageType('Ring', (_message.Message,), dict(
  DESCRIPTOR = _RING,
  __module__ = 'NavigableSpaceProto_pb2'
  # @@protoc_insertion_point(class_scope:com.navatar.protobufs.Ring)
  ))
_sym_db.RegisterMessage(Ring)


# @@protoc_insertion_point(module_scope)
