// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingMapProto.proto

package com.navatar.protobufs;

public final class BuildingMapProto {
  private BuildingMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuildingMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.navatar.protobufs.BuildingMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
     *
     * <pre>
     * The map's minimum coordinates. 
     * </pre>
     */
    boolean hasMinCoordinates();
    /**
     * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
     *
     * <pre>
     * The map's minimum coordinates. 
     * </pre>
     */
    com.navatar.protobufs.CoordinatesProto.Coordinates getMinCoordinates();
    /**
     * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
     *
     * <pre>
     * The map's minimum coordinates. 
     * </pre>
     */
    com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder getMinCoordinatesOrBuilder();

    /**
     * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
     *
     * <pre>
     * The map's maximum coordinates. 
     * </pre>
     */
    boolean hasMaxCoordinates();
    /**
     * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
     *
     * <pre>
     * The map's maximum coordinates. 
     * </pre>
     */
    com.navatar.protobufs.CoordinatesProto.Coordinates getMaxCoordinates();
    /**
     * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
     *
     * <pre>
     * The map's maximum coordinates. 
     * </pre>
     */
    com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder getMaxCoordinatesOrBuilder();

    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * The building's name. 
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * The building's name. 
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * The building's name. 
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    java.util.List<com.navatar.protobufs.FloorProto.Floor> 
        getFloorsList();
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    com.navatar.protobufs.FloorProto.Floor getFloors(int index);
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    int getFloorsCount();
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    java.util.List<? extends com.navatar.protobufs.FloorProto.FloorOrBuilder> 
        getFloorsOrBuilderList();
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    com.navatar.protobufs.FloorProto.FloorOrBuilder getFloorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.navatar.protobufs.BuildingMap}
   *
   * <pre>
   **
   * The protobuf definition for the BuildingMap class.
   * </pre>
   */
  public static final class BuildingMap extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.navatar.protobufs.BuildingMap)
      BuildingMapOrBuilder {
    // Use BuildingMap.newBuilder() to construct.
    private BuildingMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BuildingMap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BuildingMap defaultInstance;
    public static BuildingMap getDefaultInstance() {
      return defaultInstance;
    }

    public BuildingMap getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BuildingMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.navatar.protobufs.CoordinatesProto.Coordinates.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = minCoordinates_.toBuilder();
              }
              minCoordinates_ = input.readMessage(com.navatar.protobufs.CoordinatesProto.Coordinates.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(minCoordinates_);
                minCoordinates_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.navatar.protobufs.CoordinatesProto.Coordinates.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = maxCoordinates_.toBuilder();
              }
              maxCoordinates_ = input.readMessage(com.navatar.protobufs.CoordinatesProto.Coordinates.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(maxCoordinates_);
                maxCoordinates_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                floors_ = new java.util.ArrayList<com.navatar.protobufs.FloorProto.Floor>();
                mutable_bitField0_ |= 0x00000008;
              }
              floors_.add(input.readMessage(com.navatar.protobufs.FloorProto.Floor.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          floors_ = java.util.Collections.unmodifiableList(floors_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navatar.protobufs.BuildingMapProto.internal_static_com_navatar_protobufs_BuildingMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navatar.protobufs.BuildingMapProto.internal_static_com_navatar_protobufs_BuildingMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.navatar.protobufs.BuildingMapProto.BuildingMap.class, com.navatar.protobufs.BuildingMapProto.BuildingMap.Builder.class);
    }

    public static com.google.protobuf.Parser<BuildingMap> PARSER =
        new com.google.protobuf.AbstractParser<BuildingMap>() {
      public BuildingMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuildingMap(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BuildingMap> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MINCOORDINATES_FIELD_NUMBER = 1;
    private com.navatar.protobufs.CoordinatesProto.Coordinates minCoordinates_;
    /**
     * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
     *
     * <pre>
     * The map's minimum coordinates. 
     * </pre>
     */
    public boolean hasMinCoordinates() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
     *
     * <pre>
     * The map's minimum coordinates. 
     * </pre>
     */
    public com.navatar.protobufs.CoordinatesProto.Coordinates getMinCoordinates() {
      return minCoordinates_;
    }
    /**
     * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
     *
     * <pre>
     * The map's minimum coordinates. 
     * </pre>
     */
    public com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder getMinCoordinatesOrBuilder() {
      return minCoordinates_;
    }

    public static final int MAXCOORDINATES_FIELD_NUMBER = 2;
    private com.navatar.protobufs.CoordinatesProto.Coordinates maxCoordinates_;
    /**
     * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
     *
     * <pre>
     * The map's maximum coordinates. 
     * </pre>
     */
    public boolean hasMaxCoordinates() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
     *
     * <pre>
     * The map's maximum coordinates. 
     * </pre>
     */
    public com.navatar.protobufs.CoordinatesProto.Coordinates getMaxCoordinates() {
      return maxCoordinates_;
    }
    /**
     * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
     *
     * <pre>
     * The map's maximum coordinates. 
     * </pre>
     */
    public com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder getMaxCoordinatesOrBuilder() {
      return maxCoordinates_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * The building's name. 
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * The building's name. 
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     *
     * <pre>
     * The building's name. 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOORS_FIELD_NUMBER = 4;
    private java.util.List<com.navatar.protobufs.FloorProto.Floor> floors_;
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    public java.util.List<com.navatar.protobufs.FloorProto.Floor> getFloorsList() {
      return floors_;
    }
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    public java.util.List<? extends com.navatar.protobufs.FloorProto.FloorOrBuilder> 
        getFloorsOrBuilderList() {
      return floors_;
    }
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    public int getFloorsCount() {
      return floors_.size();
    }
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    public com.navatar.protobufs.FloorProto.Floor getFloors(int index) {
      return floors_.get(index);
    }
    /**
     * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
     *
     * <pre>
     * An array of the floors of this building. 
     * </pre>
     */
    public com.navatar.protobufs.FloorProto.FloorOrBuilder getFloorsOrBuilder(
        int index) {
      return floors_.get(index);
    }

    private void initFields() {
      minCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
      maxCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
      name_ = "";
      floors_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, minCoordinates_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, maxCoordinates_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      for (int i = 0; i < floors_.size(); i++) {
        output.writeMessage(4, floors_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, minCoordinates_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, maxCoordinates_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      for (int i = 0; i < floors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, floors_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.navatar.protobufs.BuildingMapProto.BuildingMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.navatar.protobufs.BuildingMapProto.BuildingMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.navatar.protobufs.BuildingMap}
     *
     * <pre>
     **
     * The protobuf definition for the BuildingMap class.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.navatar.protobufs.BuildingMap)
        com.navatar.protobufs.BuildingMapProto.BuildingMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navatar.protobufs.BuildingMapProto.internal_static_com_navatar_protobufs_BuildingMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navatar.protobufs.BuildingMapProto.internal_static_com_navatar_protobufs_BuildingMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.navatar.protobufs.BuildingMapProto.BuildingMap.class, com.navatar.protobufs.BuildingMapProto.BuildingMap.Builder.class);
      }

      // Construct using com.navatar.protobufs.BuildingMapProto.BuildingMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMinCoordinatesFieldBuilder();
          getMaxCoordinatesFieldBuilder();
          getFloorsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (minCoordinatesBuilder_ == null) {
          minCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
        } else {
          minCoordinatesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (maxCoordinatesBuilder_ == null) {
          maxCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
        } else {
          maxCoordinatesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (floorsBuilder_ == null) {
          floors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          floorsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navatar.protobufs.BuildingMapProto.internal_static_com_navatar_protobufs_BuildingMap_descriptor;
      }

      public com.navatar.protobufs.BuildingMapProto.BuildingMap getDefaultInstanceForType() {
        return com.navatar.protobufs.BuildingMapProto.BuildingMap.getDefaultInstance();
      }

      public com.navatar.protobufs.BuildingMapProto.BuildingMap build() {
        com.navatar.protobufs.BuildingMapProto.BuildingMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.navatar.protobufs.BuildingMapProto.BuildingMap buildPartial() {
        com.navatar.protobufs.BuildingMapProto.BuildingMap result = new com.navatar.protobufs.BuildingMapProto.BuildingMap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (minCoordinatesBuilder_ == null) {
          result.minCoordinates_ = minCoordinates_;
        } else {
          result.minCoordinates_ = minCoordinatesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (maxCoordinatesBuilder_ == null) {
          result.maxCoordinates_ = maxCoordinates_;
        } else {
          result.maxCoordinates_ = maxCoordinatesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (floorsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            floors_ = java.util.Collections.unmodifiableList(floors_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.floors_ = floors_;
        } else {
          result.floors_ = floorsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navatar.protobufs.BuildingMapProto.BuildingMap) {
          return mergeFrom((com.navatar.protobufs.BuildingMapProto.BuildingMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.navatar.protobufs.BuildingMapProto.BuildingMap other) {
        if (other == com.navatar.protobufs.BuildingMapProto.BuildingMap.getDefaultInstance()) return this;
        if (other.hasMinCoordinates()) {
          mergeMinCoordinates(other.getMinCoordinates());
        }
        if (other.hasMaxCoordinates()) {
          mergeMaxCoordinates(other.getMaxCoordinates());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (floorsBuilder_ == null) {
          if (!other.floors_.isEmpty()) {
            if (floors_.isEmpty()) {
              floors_ = other.floors_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFloorsIsMutable();
              floors_.addAll(other.floors_);
            }
            onChanged();
          }
        } else {
          if (!other.floors_.isEmpty()) {
            if (floorsBuilder_.isEmpty()) {
              floorsBuilder_.dispose();
              floorsBuilder_ = null;
              floors_ = other.floors_;
              bitField0_ = (bitField0_ & ~0x00000008);
              floorsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFloorsFieldBuilder() : null;
            } else {
              floorsBuilder_.addAllMessages(other.floors_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.navatar.protobufs.BuildingMapProto.BuildingMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.navatar.protobufs.BuildingMapProto.BuildingMap) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.navatar.protobufs.CoordinatesProto.Coordinates minCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.navatar.protobufs.CoordinatesProto.Coordinates, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder, com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder> minCoordinatesBuilder_;
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public boolean hasMinCoordinates() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public com.navatar.protobufs.CoordinatesProto.Coordinates getMinCoordinates() {
        if (minCoordinatesBuilder_ == null) {
          return minCoordinates_;
        } else {
          return minCoordinatesBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public Builder setMinCoordinates(com.navatar.protobufs.CoordinatesProto.Coordinates value) {
        if (minCoordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          minCoordinates_ = value;
          onChanged();
        } else {
          minCoordinatesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public Builder setMinCoordinates(
          com.navatar.protobufs.CoordinatesProto.Coordinates.Builder builderForValue) {
        if (minCoordinatesBuilder_ == null) {
          minCoordinates_ = builderForValue.build();
          onChanged();
        } else {
          minCoordinatesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public Builder mergeMinCoordinates(com.navatar.protobufs.CoordinatesProto.Coordinates value) {
        if (minCoordinatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              minCoordinates_ != com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance()) {
            minCoordinates_ =
              com.navatar.protobufs.CoordinatesProto.Coordinates.newBuilder(minCoordinates_).mergeFrom(value).buildPartial();
          } else {
            minCoordinates_ = value;
          }
          onChanged();
        } else {
          minCoordinatesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public Builder clearMinCoordinates() {
        if (minCoordinatesBuilder_ == null) {
          minCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
          onChanged();
        } else {
          minCoordinatesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public com.navatar.protobufs.CoordinatesProto.Coordinates.Builder getMinCoordinatesBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMinCoordinatesFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      public com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder getMinCoordinatesOrBuilder() {
        if (minCoordinatesBuilder_ != null) {
          return minCoordinatesBuilder_.getMessageOrBuilder();
        } else {
          return minCoordinates_;
        }
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates minCoordinates = 1;</code>
       *
       * <pre>
       * The map's minimum coordinates. 
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.navatar.protobufs.CoordinatesProto.Coordinates, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder, com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder> 
          getMinCoordinatesFieldBuilder() {
        if (minCoordinatesBuilder_ == null) {
          minCoordinatesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.navatar.protobufs.CoordinatesProto.Coordinates, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder, com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder>(
                  getMinCoordinates(),
                  getParentForChildren(),
                  isClean());
          minCoordinates_ = null;
        }
        return minCoordinatesBuilder_;
      }

      private com.navatar.protobufs.CoordinatesProto.Coordinates maxCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.navatar.protobufs.CoordinatesProto.Coordinates, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder, com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder> maxCoordinatesBuilder_;
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public boolean hasMaxCoordinates() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public com.navatar.protobufs.CoordinatesProto.Coordinates getMaxCoordinates() {
        if (maxCoordinatesBuilder_ == null) {
          return maxCoordinates_;
        } else {
          return maxCoordinatesBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public Builder setMaxCoordinates(com.navatar.protobufs.CoordinatesProto.Coordinates value) {
        if (maxCoordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          maxCoordinates_ = value;
          onChanged();
        } else {
          maxCoordinatesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public Builder setMaxCoordinates(
          com.navatar.protobufs.CoordinatesProto.Coordinates.Builder builderForValue) {
        if (maxCoordinatesBuilder_ == null) {
          maxCoordinates_ = builderForValue.build();
          onChanged();
        } else {
          maxCoordinatesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public Builder mergeMaxCoordinates(com.navatar.protobufs.CoordinatesProto.Coordinates value) {
        if (maxCoordinatesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              maxCoordinates_ != com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance()) {
            maxCoordinates_ =
              com.navatar.protobufs.CoordinatesProto.Coordinates.newBuilder(maxCoordinates_).mergeFrom(value).buildPartial();
          } else {
            maxCoordinates_ = value;
          }
          onChanged();
        } else {
          maxCoordinatesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public Builder clearMaxCoordinates() {
        if (maxCoordinatesBuilder_ == null) {
          maxCoordinates_ = com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
          onChanged();
        } else {
          maxCoordinatesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public com.navatar.protobufs.CoordinatesProto.Coordinates.Builder getMaxCoordinatesBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMaxCoordinatesFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      public com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder getMaxCoordinatesOrBuilder() {
        if (maxCoordinatesBuilder_ != null) {
          return maxCoordinatesBuilder_.getMessageOrBuilder();
        } else {
          return maxCoordinates_;
        }
      }
      /**
       * <code>optional .com.navatar.protobufs.Coordinates maxCoordinates = 2;</code>
       *
       * <pre>
       * The map's maximum coordinates. 
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.navatar.protobufs.CoordinatesProto.Coordinates, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder, com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder> 
          getMaxCoordinatesFieldBuilder() {
        if (maxCoordinatesBuilder_ == null) {
          maxCoordinatesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.navatar.protobufs.CoordinatesProto.Coordinates, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder, com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder>(
                  getMaxCoordinates(),
                  getParentForChildren(),
                  isClean());
          maxCoordinates_ = null;
        }
        return maxCoordinatesBuilder_;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * The building's name. 
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * The building's name. 
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * The building's name. 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * The building's name. 
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * The building's name. 
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * The building's name. 
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.navatar.protobufs.FloorProto.Floor> floors_ =
        java.util.Collections.emptyList();
      private void ensureFloorsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          floors_ = new java.util.ArrayList<com.navatar.protobufs.FloorProto.Floor>(floors_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.navatar.protobufs.FloorProto.Floor, com.navatar.protobufs.FloorProto.Floor.Builder, com.navatar.protobufs.FloorProto.FloorOrBuilder> floorsBuilder_;

      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public java.util.List<com.navatar.protobufs.FloorProto.Floor> getFloorsList() {
        if (floorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(floors_);
        } else {
          return floorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public int getFloorsCount() {
        if (floorsBuilder_ == null) {
          return floors_.size();
        } else {
          return floorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public com.navatar.protobufs.FloorProto.Floor getFloors(int index) {
        if (floorsBuilder_ == null) {
          return floors_.get(index);
        } else {
          return floorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder setFloors(
          int index, com.navatar.protobufs.FloorProto.Floor value) {
        if (floorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFloorsIsMutable();
          floors_.set(index, value);
          onChanged();
        } else {
          floorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder setFloors(
          int index, com.navatar.protobufs.FloorProto.Floor.Builder builderForValue) {
        if (floorsBuilder_ == null) {
          ensureFloorsIsMutable();
          floors_.set(index, builderForValue.build());
          onChanged();
        } else {
          floorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder addFloors(com.navatar.protobufs.FloorProto.Floor value) {
        if (floorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFloorsIsMutable();
          floors_.add(value);
          onChanged();
        } else {
          floorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder addFloors(
          int index, com.navatar.protobufs.FloorProto.Floor value) {
        if (floorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFloorsIsMutable();
          floors_.add(index, value);
          onChanged();
        } else {
          floorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder addFloors(
          com.navatar.protobufs.FloorProto.Floor.Builder builderForValue) {
        if (floorsBuilder_ == null) {
          ensureFloorsIsMutable();
          floors_.add(builderForValue.build());
          onChanged();
        } else {
          floorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder addFloors(
          int index, com.navatar.protobufs.FloorProto.Floor.Builder builderForValue) {
        if (floorsBuilder_ == null) {
          ensureFloorsIsMutable();
          floors_.add(index, builderForValue.build());
          onChanged();
        } else {
          floorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder addAllFloors(
          java.lang.Iterable<? extends com.navatar.protobufs.FloorProto.Floor> values) {
        if (floorsBuilder_ == null) {
          ensureFloorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, floors_);
          onChanged();
        } else {
          floorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder clearFloors() {
        if (floorsBuilder_ == null) {
          floors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          floorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public Builder removeFloors(int index) {
        if (floorsBuilder_ == null) {
          ensureFloorsIsMutable();
          floors_.remove(index);
          onChanged();
        } else {
          floorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public com.navatar.protobufs.FloorProto.Floor.Builder getFloorsBuilder(
          int index) {
        return getFloorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public com.navatar.protobufs.FloorProto.FloorOrBuilder getFloorsOrBuilder(
          int index) {
        if (floorsBuilder_ == null) {
          return floors_.get(index);  } else {
          return floorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public java.util.List<? extends com.navatar.protobufs.FloorProto.FloorOrBuilder> 
           getFloorsOrBuilderList() {
        if (floorsBuilder_ != null) {
          return floorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(floors_);
        }
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public com.navatar.protobufs.FloorProto.Floor.Builder addFloorsBuilder() {
        return getFloorsFieldBuilder().addBuilder(
            com.navatar.protobufs.FloorProto.Floor.getDefaultInstance());
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public com.navatar.protobufs.FloorProto.Floor.Builder addFloorsBuilder(
          int index) {
        return getFloorsFieldBuilder().addBuilder(
            index, com.navatar.protobufs.FloorProto.Floor.getDefaultInstance());
      }
      /**
       * <code>repeated .com.navatar.protobufs.Floor floors = 4;</code>
       *
       * <pre>
       * An array of the floors of this building. 
       * </pre>
       */
      public java.util.List<com.navatar.protobufs.FloorProto.Floor.Builder> 
           getFloorsBuilderList() {
        return getFloorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.navatar.protobufs.FloorProto.Floor, com.navatar.protobufs.FloorProto.Floor.Builder, com.navatar.protobufs.FloorProto.FloorOrBuilder> 
          getFloorsFieldBuilder() {
        if (floorsBuilder_ == null) {
          floorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.navatar.protobufs.FloorProto.Floor, com.navatar.protobufs.FloorProto.Floor.Builder, com.navatar.protobufs.FloorProto.FloorOrBuilder>(
                  floors_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          floors_ = null;
        }
        return floorsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.navatar.protobufs.BuildingMap)
    }

    static {
      defaultInstance = new BuildingMap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.navatar.protobufs.BuildingMap)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_navatar_protobufs_BuildingMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_navatar_protobufs_BuildingMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026BuildingMapProto.proto\022\025com.navatar.pr" +
      "otobufs\032\020FloorProto.proto\032\026CoordinatesPr" +
      "oto.proto\"\301\001\n\013BuildingMap\022:\n\016minCoordina" +
      "tes\030\001 \001(\0132\".com.navatar.protobufs.Coordi" +
      "nates\022:\n\016maxCoordinates\030\002 \001(\0132\".com.nava" +
      "tar.protobufs.Coordinates\022\014\n\004name\030\003 \001(\t\022" +
      ",\n\006floors\030\004 \003(\0132\034.com.navatar.protobufs." +
      "Floor"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.navatar.protobufs.FloorProto.getDescriptor(),
          com.navatar.protobufs.CoordinatesProto.getDescriptor(),
        }, assigner);
    internal_static_com_navatar_protobufs_BuildingMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_navatar_protobufs_BuildingMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_navatar_protobufs_BuildingMap_descriptor,
        new java.lang.String[] { "MinCoordinates", "MaxCoordinates", "Name", "Floors", });
    com.navatar.protobufs.FloorProto.getDescriptor();
    com.navatar.protobufs.CoordinatesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
