// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoordinatesProto.proto

package com.navatar.protobufs;

public final class CoordinatesProto {
  private CoordinatesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CoordinatesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.navatar.protobufs.Coordinates)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double x = 1;</code>
     *
     * <pre>
     * The x coordinate. 
     * </pre>
     */
    boolean hasX();
    /**
     * <code>optional double x = 1;</code>
     *
     * <pre>
     * The x coordinate. 
     * </pre>
     */
    double getX();

    /**
     * <code>optional double y = 2;</code>
     *
     * <pre>
     * The y coordinate. 
     * </pre>
     */
    boolean hasY();
    /**
     * <code>optional double y = 2;</code>
     *
     * <pre>
     * The y coordinate. 
     * </pre>
     */
    double getY();
  }
  /**
   * Protobuf type {@code com.navatar.protobufs.Coordinates}
   *
   * <pre>
   **
   * The protobuf for the Coordinates class used to define points in the map.
   * </pre>
   */
  public static final class Coordinates extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.navatar.protobufs.Coordinates)
      CoordinatesOrBuilder {
    // Use Coordinates.newBuilder() to construct.
    private Coordinates(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Coordinates(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Coordinates defaultInstance;
    public static Coordinates getDefaultInstance() {
      return defaultInstance;
    }

    public Coordinates getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Coordinates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navatar.protobufs.CoordinatesProto.internal_static_com_navatar_protobufs_Coordinates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navatar.protobufs.CoordinatesProto.internal_static_com_navatar_protobufs_Coordinates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.navatar.protobufs.CoordinatesProto.Coordinates.class, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder.class);
    }

    public static com.google.protobuf.Parser<Coordinates> PARSER =
        new com.google.protobuf.AbstractParser<Coordinates>() {
      public Coordinates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Coordinates(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Coordinates> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>optional double x = 1;</code>
     *
     * <pre>
     * The x coordinate. 
     * </pre>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double x = 1;</code>
     *
     * <pre>
     * The x coordinate. 
     * </pre>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>optional double y = 2;</code>
     *
     * <pre>
     * The y coordinate. 
     * </pre>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double y = 2;</code>
     *
     * <pre>
     * The y coordinate. 
     * </pre>
     */
    public double getY() {
      return y_;
    }

    private void initFields() {
      x_ = 0D;
      y_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.navatar.protobufs.CoordinatesProto.Coordinates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.navatar.protobufs.CoordinatesProto.Coordinates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.navatar.protobufs.Coordinates}
     *
     * <pre>
     **
     * The protobuf for the Coordinates class used to define points in the map.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.navatar.protobufs.Coordinates)
        com.navatar.protobufs.CoordinatesProto.CoordinatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navatar.protobufs.CoordinatesProto.internal_static_com_navatar_protobufs_Coordinates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navatar.protobufs.CoordinatesProto.internal_static_com_navatar_protobufs_Coordinates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.navatar.protobufs.CoordinatesProto.Coordinates.class, com.navatar.protobufs.CoordinatesProto.Coordinates.Builder.class);
      }

      // Construct using com.navatar.protobufs.CoordinatesProto.Coordinates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navatar.protobufs.CoordinatesProto.internal_static_com_navatar_protobufs_Coordinates_descriptor;
      }

      public com.navatar.protobufs.CoordinatesProto.Coordinates getDefaultInstanceForType() {
        return com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance();
      }

      public com.navatar.protobufs.CoordinatesProto.Coordinates build() {
        com.navatar.protobufs.CoordinatesProto.Coordinates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.navatar.protobufs.CoordinatesProto.Coordinates buildPartial() {
        com.navatar.protobufs.CoordinatesProto.Coordinates result = new com.navatar.protobufs.CoordinatesProto.Coordinates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navatar.protobufs.CoordinatesProto.Coordinates) {
          return mergeFrom((com.navatar.protobufs.CoordinatesProto.Coordinates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.navatar.protobufs.CoordinatesProto.Coordinates other) {
        if (other == com.navatar.protobufs.CoordinatesProto.Coordinates.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.navatar.protobufs.CoordinatesProto.Coordinates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.navatar.protobufs.CoordinatesProto.Coordinates) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>optional double x = 1;</code>
       *
       * <pre>
       * The x coordinate. 
       * </pre>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double x = 1;</code>
       *
       * <pre>
       * The x coordinate. 
       * </pre>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 1;</code>
       *
       * <pre>
       * The x coordinate. 
       * </pre>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 1;</code>
       *
       * <pre>
       * The x coordinate. 
       * </pre>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>optional double y = 2;</code>
       *
       * <pre>
       * The y coordinate. 
       * </pre>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double y = 2;</code>
       *
       * <pre>
       * The y coordinate. 
       * </pre>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 2;</code>
       *
       * <pre>
       * The y coordinate. 
       * </pre>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 2;</code>
       *
       * <pre>
       * The y coordinate. 
       * </pre>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.navatar.protobufs.Coordinates)
    }

    static {
      defaultInstance = new Coordinates(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.navatar.protobufs.Coordinates)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_navatar_protobufs_Coordinates_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_navatar_protobufs_Coordinates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026CoordinatesProto.proto\022\025com.navatar.pr" +
      "otobufs\"#\n\013Coordinates\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002" +
      " \001(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_navatar_protobufs_Coordinates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_navatar_protobufs_Coordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_navatar_protobufs_Coordinates_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
